const users = require('./users/users.service.js');
const testa = require('./testa/testa.service.js');
const version = require('./version/version.service.js');
const versionStatus = require('./version-status/version-status.service.js');
const activity = require('./activity/activity.service.js');
const activityToType = require('./activity-to-type/activity-to-type.service.js');
const activityToUserType = require('./activity-to-user-type/activity-to-user-type.service.js');
const activityType = require('./activity-type/activity-type.service.js');
const billing = require('./billing/billing.service.js');
const billingActivity = require('./billing-activity/billing-activity.service.js');
const billingApproval = require('./billing-approval/billing-approval.service.js');
const billingEstimate = require('./billing-estimate/billing-estimate.service.js');
const billingStatus = require('./billing-status/billing-status.service.js');
const campaign = require('./campaign/campaign.service.js');
const comment = require('./comment/comment.service.js');
const commentType = require('./comment-type/comment-type.service.js');
const customer = require('./customer/customer.service.js');
const customerContact = require('./customer-contact/customer-contact.service.js');
const userType = require('./user-type/user-type.service.js');
const userTypeClass = require('./user-type-class/user-type-class.service.js');
const userTypeProjectPermission = require('./user-type-project-permission/user-type-project-permission.service.js');
const projectPermissions = require('./project-permissions/project-permissions.service.js');
const customerPrice = require('./customer-price/customer-price.service.js');
const project = require('./project/project.service.js');
const status = require('./status/status.service.js');
const projectToCampaign = require('./project-to-campaign/project-to-campaign.service.js');
const projectHistory = require('./project-history/project-history.service.js');
const projectToCampaignUser = require('./project-to-campaign-user/project-to-campaign-user.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(testa);
  app.configure(version);
  app.configure(versionStatus);
  app.configure(activity);
  app.configure(activityToType);
  app.configure(activityToUserType);
  app.configure(activityType);
  app.configure(billing);
  app.configure(billingActivity);
  app.configure(billingApproval);
  app.configure(billingEstimate);
  app.configure(billingStatus);
  app.configure(campaign);
  app.configure(comment);
  app.configure(commentType);
  app.configure(customer);
  app.configure(customerContact);
  app.configure(userType);
  app.configure(userTypeClass);
  app.configure(userTypeProjectPermission);
  app.configure(projectPermissions);
  app.configure(customerPrice);
  app.configure(project);
  app.configure(status);
  app.configure(projectToCampaign);
  app.configure(projectHistory);
  app.configure(projectToCampaignUser);
};
